---
- hosts: all
  become: true
  tasks:

  - name: install nginx package
    package:
      name: 
        - "{{ nginx }}"
        - "{{ php }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
